services:
    oro_infinite_pay.form.type.debtor_data:
        class: 'Oro\Bundle\InfinitePayBundle\Form\Type\DebtorDataType'
        tags:
            - { name: form.type, alias: oro_infinite_pay_debtor_data }

    oro_infinite_pay.form.type.settings:
        class: 'Oro\Bundle\InfinitePayBundle\Form\Type\InfinitePaySettingsType'
        tags:
            - { name: form.type }
