config:
    paths:
        'oroinfinitepay/js/app/components/payment-additional-fields-component': 'bundles/oroinfinitepay/js/app/components/payment-additional-fields-component.js'
        'oroinfinitepay/js/app/components/payment-method-component': 'bundles/oroinfinitepay/js/app/components/payment-method-component.js'
