Oro\Bundle\CustomerBundle\Entity\Customer:
    constraints:
        - Oro\Bundle\InfinitePayBundle\Validator\Constraints\CustomerRequireVatId: ~

Oro\Bundle\CustomerBundle\Entity\CustomerAddress:
    properties:
        frontendOwner:
            - Oro\Bundle\InfinitePayBundle\Validator\Constraints\CustomerRequireVatId: ~

Oro\Bundle\InfinitePayBundle\Entity\InfinitePaySettings:
    properties:
        infinitePayLabels:
            - NotBlank: ~
        infinitePayShortLabels:
            - NotBlank: ~
        infinitePayClientRef:
            - NotBlank: ~
        infinitePayUsername:
            - NotBlank: ~
        infinitePayPassword:
            - NotBlank: ~
        infinitePaySecret:
            - NotBlank: ~
